---
title: "Statistical Analysis of Genetic Algorithm"
output: html_notebook
fig_width: 6 
fig_height: 8 
---


# Hypervolume Analysis


```{r}
require(data.table)
file1 <- read.csv("10_Knapsack_Runs/10kp_200GenAllRuns.csv")
file2 <- read.csv("5_Knapsack_Runs/5kp_200GenAllRuns.csv")
file3 <- read.csv("3_Knapsack_Runs/3kp_200GenAllRuns.csv")

three_kp <- rbind(file1, file2, file3)
#three_kp<- three_kp[three_kp$instance_name %like% 'r_300', ]

three_kp$block <- 0

knapsack_count = c(3,5,10)
unique_instances = unique(three_kp$instance_name)
block_count = 3*length(unique_instances)
block_matrix = matrix(1:block_count, nrow =3, ncol=length(unique_instances))
rownames(block_matrix) <- knapsack_count
colnames(block_matrix) <- unique_instances
for (i in 1:nrow(three_kp)){
  three_kp[i, "block"] <- block_matrix[toString(three_kp[i,"n_kp"]), three_kp[i,"instance_name"]]
}

hv_pop <- data.frame(three_kp['pop_size'], three_kp['hypervolume'])
hv_mut <- data.frame(three_kp['mut_rate'], three_kp['hypervolume'])
```


```{r}
plot(hv_pop)
```

```{r}
plot(hv_mut)
```

```{r}
boxplot(hypervolume~mut_rate, data = three_kp)
```
```{r}
boxplot(hypervolume~pop_size, data = three_kp)

```


```{r}
average_hypervolume = c(0,0,0,0,0,0,0,0,0)
mut_rates = c(.1,.2,.3,.4,.5,.6,.7,.8,.9)
for (i in 1:9){
  average_hypervolume[i] = mean(three_kp[three_kp$mut_rate == mut_rates[i], ][['hypervolume']])
}
plot(mut_rates, average_hypervolume)
```
```{r}
average_hypervolume = c(0,0,0,0)
pop_sizes = c(100,150,200,250)
for (i in 1:4){
  average_hypervolume[i] = mean(three_kp[three_kp$pop_size == pop_sizes[i], ][['hypervolume']])
}
plot(pop_sizes, average_hypervolume)
```


```{r}
three_kp <- within(three_kp,{
  instance_name <-factor(instance_name)
  mut_rate <- factor(mut_rate)
  pop_size <-factor(pop_size)
  n_kp <-factor(n_kp)
  block <- factor(block)
})

three_all_mut_hv <-aov(hypervolume~block+mut_rate, data = three_kp)
three_all_pop_hv <-aov(hypervolume~block+pop_size, data = three_kp)
three_all_two_interacting_hv <-aov(hypervolume~block+pop_size*mut_rate, data = three_kp)
print(summary(three_all_mut_hv))
print(summary(three_all_pop_hv))
print(summary(three_all_two_interacting_hv))

tukey.mut_hv<-TukeyHSD(three_all_mut_hv, conf.level = 0.99)
tukey.pop_hv <-TukeyHSD(three_all_pop_hv, conf.level = 0.99)
```


```{r fig.height = 10, fig.width = 10, fig.align = "center"}
require(grDevices)
print(tukey.mut_hv$mut_rate)
plot(tukey.mut_hv, las = 2, font.main=5)
```

```{r}
require(stringr)
mut_rates = c(.1,.2,.3,.4,.5,.6,.7,.8,.9)
mut_dif = matrix(0.0, nrow = 9, ncol = 9)
mut_sig = matrix(1, nrow = 9, ncol = 9)
rownames(mut_dif) <- mut_rates
colnames(mut_dif) <- mut_rates
rownames(mut_sig) <- mut_rates
colnames(mut_sig) <- mut_rates
typeof(tukey.mut_hv$mut_rate)
tukey_mut <- data.frame(tukey.mut_hv$mut_rate)
for (i in 1:nrow(tukey_mut)){
  row_name <- rownames(tukey_mut)[i]
  split = str_split(row_name, "-")
  #print(split[[1]][2])
  v1 = split[[1]][1]
  v2 = split[[1]][2]
  mut_dif[v1, v2] = tukey_mut[i, 'diff']
  mut_dif[v2, v1] = -1*tukey_mut[i, 'diff']
  if(tukey_mut[i, 'p.adj'] <= .01){
    mut_sig[v1, v2] = tukey_mut[i, 'p.adj']
    mut_sig[v2, v1] = tukey_mut[i, 'p.adj']
  }
}
formatC(mut_dif, format = "e", digits = 2)
formatC(mut_sig, format = "e", digits = 2)

```
```{r}
heatmap(mut_dif, Colv = NA, Rowv = NA, scale="column")
```

```{r fig.height = 5, fig.width = 5, fig.align = "center"}
require(grDevices)
print(tukey.pop_hv$pop_size)
plot(tukey.pop_hv)
```


```{r}
require(stringr)
pop_sizes = c(100,150,200,250)
pop_dif = matrix(0.0, nrow = 4, ncol = 4)
pop_sig = matrix(1, nrow = 4, ncol = 4)
rownames(pop_dif) <- pop_sizes
colnames(pop_dif) <- pop_sizes
rownames(pop_sig) <- pop_sizes
colnames(pop_sig) <- pop_sizes
tukey_pop <- data.frame(tukey.pop_hv$pop_size)
for (i in 1:nrow(tukey_pop)){
  row_name <- rownames(tukey_pop)[i]
  split = str_split(row_name, "-")
  #print(split[[1]][2])
  v1 = split[[1]][1]
  v2 = split[[1]][2]
  pop_dif[v1, v2] = tukey_pop[i, 'diff']
  pop_dif[v2, v1] = -1*tukey_pop[i, 'diff']
  if(tukey_pop[i, 'p.adj'] <= .01){
    pop_sig[v1, v2] = tukey_pop[i, 'p.adj']
    pop_sig[v2, v1] = tukey_pop[i, 'p.adj']
  }
}
formatC(pop_dif, format = "e", digits = 2)
formatC(pop_sig, format = "e", digits = 2)
```

```{r}
heatmap(pop_dif, Colv = NA, Rowv = NA, scale="column")

```



